name: TheCodeCore
main: EversoftTeam\Main
author: EversoftTeam
version: 1.0 beta
api: 3.0.0

permissions:
  code.cmd:
    description: main the code permission
    default: true
    children:
      code.cmd.particles:
        description: particles permission
        default: op
      code.cmd.particles.helix:
        description: helix particle permission
        default: false
      code.cmd.pets:
        description: pets permission
        default: op
      code.cmd.rank:
        description: ranks permission
        default: op
      code.cmd.stats:
        description: stats permission
        default: true
      code.cmd.tops:
        description: tops permission
        default: true
      code.cmd.hub:
        description: hub permission
        default: true
      code.cmd.gadgets:
        description: gadgets permission
        default: true
      code.cmd.gadgets.tnt:
        description: gadget tnt permission
        default: false
